(()=>{'use strict';
const T=window.LR_TRANSIT,S=window.LR_SCHEDULE,APP=window.__LR_APP_TEST__,$=id=>document.getElementById(id);
if(!T||!S||!APP)return;
const state=APP.state;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
const fmtDuration=m=>{m=Math.max(0,Math.round(m||0));return m>=60?`${Math.floor(m/60)} h${m%60?' '+m%60+' min':''}`:`${m} min`};
const fmtDistance=m=>m>=1000?`${(m/1000).toFixed(m>=10000?0:1).replace('.',',')} km`:`${Math.round(m)} m`;
const dayNames=['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'];
class Heap{constructor(){this.a=[]}push(node,p){let a=this.a,i=a.length;a.push([p,node]);while(i){let q=(i-1)>>1;if(a[q][0]<=p)break;a[i]=a[q];i=q}a[i]=[p,node]}pop(){let a=this.a;if(!a.length)return null;let root=a[0],last=a.pop();if(a.length){a[0]=last;let i=0;for(;;){let l=i*2+1,r=l+1,b=i;if(l<a.length&&a[l][0]<a[b][0])b=l;if(r<a.length&&a[r][0]<a[b][0])b=r;if(b===i)break;[a[i],a[b]]=[a[b],a[i]];i=b}}return[root[1],root[0]]}get length(){return this.a.length}}
function lineInfo(code){return T.lineInfo['BUS-'+code]||Object.values(T.lineInfo).find(x=>x.line===code)||{line:code,color:'#64748b',mode:'Transport',name:'Ligne '+code}}
function modeKey(mode){mode=norm(mode);return mode.includes('bus')?'bus':mode.includes('tram')?'tram':mode.includes('metro')?'metro':'train'}
function serviceKey(d){let n=d.getDay();return n===5?'friday':n===6?'saturday':n===0?'sunday':'weekday'}
function localISO(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function serviceMoment(date){let actual=new Date(date),base=new Date(actual.getFullYear(),actual.getMonth(),actual.getDate()),m=actual.getHours()*60+actual.getMinutes();if(m<240){base.setDate(base.getDate()-1);m+=1440}return{actual,base,minutes:m,key:serviceKey(base)}}
function atMinute(base,m){let d=new Date(base);d.setMinutes(m);return d}
function fmtClock(base,m){return atMinute(base,m).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function fmtDateTime(base,m){let d=atMinute(base,m);return `${dayNames[d.getDay()]} ${d.getDate()} ${d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','')} · ${d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`}
class ExactRouter{
  constructor(){
    this.nodes=T.serviceNodes;this.N=this.nodes.length;this.byLineName=new Map;this.byPhysical=new Map;this.rideEdges=new Map;this.rideAdj=new Map;this.transferAdj=Array.from({length:this.N},()=>[]);this.seqCache=new WeakMap;this.pathCache=new Map;this.cache=null;
    this.nodes.forEach((n,i)=>{let k=`${n[4]}|${norm(n[1])}`;if(!this.byLineName.has(k))this.byLineName.set(k,[]);this.byLineName.get(k).push(i);let p=`${Math.round(n[2]*10)}|${Math.round(n[3]*10)}`;if(!this.byPhysical.has(p))this.byPhysical.set(p,[]);this.byPhysical.get(p).push(i)});
    T.edges.forEach((e,idx)=>{if(e[3]===0){let k=`${e[4]}|${e[0]}|${e[1]}`;if(!this.rideEdges.has(k)||e[2]<this.rideEdges.get(k).edge[2])this.rideEdges.set(k,{edge:e,index:idx});if(!this.rideAdj.has(e[4]))this.rideAdj.set(e[4],Array.from({length:this.N},()=>[]));this.rideAdj.get(e[4])[e[0]].push({to:e[1],time:e[2],coords:e[7]||[]})}else this.transferAdj[e[0]].push({to:e[1],time:+e[2]||1.5,kind:e[3],coords:e[7]||[]})});
  }
  candidates(line,name){let exact=this.byLineName.get(`${line}|${norm(name)}`);if(exact?.length)return exact;let target=norm(name),best=[],score=0;for(const [k,ids] of this.byLineName){if(!k.startsWith(line+'|'))continue;let n=k.slice(line.length+1),a=new Set(target.split(' ')),b=new Set(n.split(' ')),hit=[...a].filter(x=>b.has(x)).length,q=hit/Math.max(a.size,b.size,1);if(n.includes(target)||target.includes(n))q+=.35;if(q>score){score=q;best=ids}}return score>.52?best:[]}
  resolveSequence(line,stops,owner){if(owner&&this.seqCache.has(owner))return this.seqCache.get(owner);let sets=stops.map(x=>this.candidates(line,Array.isArray(x)?x[0]:x)),dp=[],pr=[];for(let i=0;i<sets.length;i++){dp[i]=new Array(sets[i].length).fill(Infinity);pr[i]=new Array(sets[i].length).fill(-1);if(!i){dp[i].fill(0);continue}for(let j=0;j<sets[i].length;j++)for(let k=0;k<sets[i-1].length;k++){let a=sets[i-1][k],b=sets[i][j],na=this.nodes[a],nb=this.nodes[b],direct=this.rideEdges.has(`${line}|${a}|${b}`),cost=dp[i-1][k]+(direct?.05:18+Math.hypot(na[2]-nb[2],na[3]-nb[3])/60);if(cost<dp[i][j]){dp[i][j]=cost;pr[i][j]=k}}}let out=new Array(sets.length).fill(null),last=sets.length-1;if(last>=0&&sets[last].length){let j=dp[last].indexOf(Math.min(...dp[last]));for(let i=last;i>=0;i--){out[i]=sets[i][j]??null;j=pr[i][j]}}if(owner)this.seqCache.set(owner,out);return out}
  addTrip(cache,trip){let idx=cache.trips.length;cache.trips.push(trip);for(let i=0;i<trip.nodes.length-1;i++){let n=trip.nodes[i];if(n==null)continue;cache.boardings[n].push({t:trip.times[i],trip:idx,i});cache.patterns[n].add(trip.pattern)}}
  addServiceDay(cache,date,shift){let key=serviceKey(date);
    for(const [line,data] of Object.entries(S.rail)){for(const block of data.x||[]){if(block.d!==key)continue;let mapped=this.resolveSequence(line,block.s,block);for(const mission of block.m||[]){let nodes=[],times=[],names=[];for(let i=0;i<mission[5].length;i++){let tm=mission[5][i],node=mapped[i];if(tm==null||tm<0||node==null)continue;nodes.push(node);times.push(tm+shift);names.push(block.s[i][0])}if(nodes.length<2)continue;let info=lineInfo(line);this.addTrip(cache,{line,mode:data.m||info.mode,color:info.color||'#3478d4',code:mission[0],destination:mission[3]||block.b,nodes,times,names,pattern:`${line}|${nodes.join(',')}|${mission[3]||block.b}`})}}}
    for(const [line,data] of Object.entries(S.bus)){let day=data.d?.[key];if(!day)continue;for(const dir of day.x||[]){let mapped=this.resolveSequence(line,dir.s,dir),valid=[];for(let i=0;i<dir.s.length;i++)if(mapped[i]!=null)valid.push(i);if(valid.length<2)continue;let info=lineInfo(line);for(const dep of dir.t||[]){let nodes=valid.map(i=>mapped[i]),times=valid.map(i=>dep+(+dir.s[i][1]||0)+shift),names=valid.map(i=>dir.s[i][0]);this.addTrip(cache,{line,mode:'Bus',color:info.color||'#735acb',code:`${line}-${dir.k}-${Math.round(dep)}`,destination:dir.b,nodes,times,names,pattern:`${line}|${dir.k}|${nodes.join(',')}`})}}}
  }
  timetable(base){let next=new Date(base);next.setDate(next.getDate()+1);let key=`${localISO(base)}|${serviceKey(base)}|${serviceKey(next)}`;if(this.cache?.key===key)return this.cache;let c={key,trips:[],boardings:Array.from({length:this.N},()=>[]),patterns:Array.from({length:this.N},()=>new Set),base};this.addServiceDay(c,base,0);this.addServiceDay(c,next,1440);for(let i=0;i<this.N;i++)c.boardings[i].sort((a,b)=>a.t-b.t);this.cache=c;return c}
  lowerBound(a,t){let l=0,r=a.length;while(l<r){let m=(l+r)>>1;if(a[m].t<t)l=m+1;else r=m}return l}
  physicalCandidates(point,cache,limit=10){let groups=[];for(const [key,ids] of this.byPhysical){if(!ids.some(i=>cache.boardings[i].length))continue;let n=this.nodes[ids[0]],d=Math.hypot(n[2]-point.x,n[3]-point.z);groups.push({key,ids,x:n[2],z:n[3],d})}groups.sort((a,b)=>a.d-b.d);let close=groups.filter(x=>x.d<=1600).slice(0,limit);return close.length?close:groups.slice(0,limit)}
  walkingRoute(a,b){let r=APP.roadRoute(a,b,'walk');if(r)return r;let d=Math.hypot(a.x-b.x,a.z-b.z);return{minutes:d/50,distance:d,coords:[a.x,a.z,b.x,b.z],groups:[]}}
  prepareEndpoints(a,b,cache){let starts=[],ends=new Map;for(const g of this.physicalCandidates(a,cache,9)){let walk=this.walkingRoute(a,{x:g.x,z:g.z,name:this.nodes[g.ids[0]][1]});for(const node of g.ids)starts.push({node,time:walk.minutes,walk})}for(const g of this.physicalCandidates(b,cache,9)){let walk=this.walkingRoute({x:g.x,z:g.z,name:this.nodes[g.ids[0]][1]},b);for(const node of g.ids)if(!ends.has(node)||walk.minutes<ends.get(node).walk.minutes)ends.set(node,{walk})}return{starts,ends}}
  search(a,b,moment,banned=new Set,prepared=null,allowedModes=null){let cache=this.timetable(moment.base),ep=prepared||this.prepareEndpoints(a,b,cache),arr=new Float64Array(this.N),prev=new Array(this.N),heap=new Heap;arr.fill(Infinity);for(const s of ep.starts){let t=moment.minutes+s.time;if(t<arr[s.node]){arr[s.node]=t;prev[s.node]={type:'access',from:-1,walk:s.walk};heap.push(s.node,t)}}let best=null,bestTime=Infinity;
    while(heap.length){let [u,t]=heap.pop();if(t!==arr[u])continue;if(t>=bestTime)break;let eg=ep.ends.get(u);if(eg&&t+eg.walk.minutes<bestTime){bestTime=t+eg.walk.minutes;best={node:u,egress:eg.walk}}
      for(const e of this.transferAdj[u]){let nt=t+e.time;if(nt<arr[e.to]&&nt<bestTime){arr[e.to]=nt;prev[e.to]={type:'transfer',from:u,edge:e};heap.push(e.to,nt)}}
      let bs=cache.boardings[u],pos=this.lowerBound(bs,t-.001),seen=new Set,need=cache.patterns[u].size,scanned=0;for(let q=pos;q<bs.length&&scanned<120;q++,scanned++){let x=bs[q],trip=cache.trips[x.trip];if(x.t>t+420||x.t>=bestTime)break;if(banned.has(trip.line)||seen.has(trip.pattern)||(allowedModes&&!allowedModes.has(modeKey(trip.mode))))continue;seen.add(trip.pattern);for(let j=x.i+1;j<trip.nodes.length;j++){let v=trip.nodes[j],nt=trip.times[j];if(nt<arr[v]&&nt<bestTime){arr[v]=nt;prev[v]={type:'ride',from:u,trip:x.trip,fromIndex:x.i,toIndex:j};heap.push(v,nt)}}if(seen.size>=need)break}
    }
    if(!best)return null;let raw=[],u=best.node;while(u>=0&&prev[u]){let p=prev[u];raw.push({...p,to:u});if(p.type==='access')break;u=p.from}raw.reverse();let steps=[],clock=moment.minutes;for(const p of raw){if(p.type==='access'){if(p.walk.distance>15)steps.push({kind:'walk',fromTime:clock,toTime:clock+p.walk.minutes,minutes:p.walk.minutes,distance:p.walk.distance,coords:p.walk.coords,title:`Marcher jusqu’à ${this.nodes[p.to][1]}`,toNode:p.to});clock+=p.walk.minutes}else if(p.type==='transfer'){let from=this.nodes[p.from],to=this.nodes[p.to];steps.push({kind:p.edge.kind===1?'transfer':'walk',fromTime:clock,toTime:clock+p.edge.time,minutes:p.edge.time,distance:p.edge.kind===2?Math.hypot(from[2]-to[2],from[3]-to[3]):0,coords:p.edge.coords,title:p.edge.kind===1?`Correspondance à ${from[1]}`:`Marcher vers ${to[1]}`,fromNode:p.from,toNode:p.to});clock+=p.edge.time}else{let trip=cache.trips[p.trip],dep=trip.times[p.fromIndex],ar=trip.times[p.toIndex];if(dep-clock>.55)steps.push({kind:'wait',fromTime:clock,toTime:dep,minutes:dep-clock,title:`Attendre la ligne ${trip.line}`,atNode:p.from});steps.push({kind:'ride',line:trip.line,mode:trip.mode,color:trip.color,tripCode:trip.code,destination:trip.destination,from:this.nodes[p.from][1],to:this.nodes[p.to][1],fromNode:p.from,toNode:p.to,fromIndex:p.fromIndex,toIndex:p.toIndex,trip,fromTime:dep,toTime:ar,minutes:ar-dep,stops:p.toIndex-p.fromIndex});clock=ar}}
    if(best.egress.distance>15){steps.push({kind:'walk',fromTime:clock,toTime:clock+best.egress.minutes,minutes:best.egress.minutes,distance:best.egress.distance,coords:best.egress.coords,title:`Marcher jusqu’à ${b.name}`});clock+=best.egress.minutes}steps=this.compactSteps(steps);let result={departure:moment.minutes,arrival:clock,minutes:clock-moment.minutes,steps,base:moment.base,a,b};this.decorate(result);return result}
  linePath(line,start,end){let key=`${line}|${start}|${end}`;if(this.pathCache.has(key))return this.pathCache.get(key);let direct=this.rideEdges.get(key);if(direct){let v=direct.edge[7]||[];this.pathCache.set(key,v);return v}let adj=this.rideAdj.get(line);if(!adj)return[this.nodes[start][2],this.nodes[start][3],this.nodes[end][2],this.nodes[end][3]];let d=new Float64Array(this.N),prev=new Array(this.N),h=new Heap;d.fill(Infinity);d[start]=0;h.push(start,0);while(h.length){let[u,du]=h.pop();if(du!==d[u])continue;if(u===end)break;for(const e of adj[u]){let nd=du+e.time;if(nd<d[e.to]){d[e.to]=nd;prev[e.to]={from:u,e};h.push(e.to,nd)}}}if(!isFinite(d[end]))return[this.nodes[start][2],this.nodes[start][3],this.nodes[end][2],this.nodes[end][3]];let edges=[],u=end;while(u!==start){let p=prev[u];if(!p)break;edges.push(p.e);u=p.from}edges.reverse();let out=[];for(const e of edges){let c=e.coords?.length?e.coords:[this.nodes[start][2],this.nodes[start][3],this.nodes[end][2],this.nodes[end][3]];out.push(...c.slice(out.length?2:0))}this.pathCache.set(key,out);return out}
  compactSteps(steps){let out=[];for(const src of steps){let s={...src,coords:src.coords?[...src.coords]:src.coords},moving=s.kind==='walk'||s.kind==='transfer',last=out.at(-1);if(moving&&last&&(last.kind==='walk'||last.kind==='transfer')){let joined=[...(last.coords||[])],next=s.coords||[];if(next.length){let cut=joined.length&&Math.hypot(joined.at(-2)-next[0],joined.at(-1)-next[1])<35?2:0;joined.push(...next.slice(cut))}last.kind=last.kind==='transfer'||s.kind==='transfer'?'transfer':'walk';last.toTime=s.toTime;last.minutes=last.toTime-last.fromTime;last.distance=(last.distance||0)+(s.distance||0);last.coords=joined;last.toNode=s.toNode??last.toNode;let target=last.toNode!=null?this.nodes[last.toNode]?.[1]:null;last.title=last.kind==='transfer'?`Correspondance${target?' vers '+target:''}`:s.title}else out.push(s)}return out}
  decorate(r){let overlay=[],stops=[];for(const step of r.steps){if(step.kind==='ride'){let coords=[];for(let i=step.fromIndex;i<step.toIndex;i++){let c=this.linePath(step.line,step.trip.nodes[i],step.trip.nodes[i+1]);coords.push(...c.slice(coords.length?2:0))}step.coords=coords;overlay.push({coords,color:step.color,width:7});let a=this.nodes[step.fromNode],b=this.nodes[step.toNode];stops.push({x:a[2],z:a[3],color:step.color,label:a[1],major:true},{x:b[2],z:b[3],color:step.color,label:b[1],major:true})}else if((step.kind==='walk'||step.kind==='transfer')&&step.coords?.length)overlay.push({coords:step.coords,color:'#74808b',width:3.5,dash:true})}r.overlay=overlay;r.stops=stops;let lines=r.steps.filter(x=>x.kind==='ride').map(x=>x.line);r.signature=lines.join('>')||'walk';r.walkMinutes=r.steps.filter(x=>x.kind==='walk').reduce((a,b)=>a+b.minutes,0);r.transfers=Math.max(0,lines.length-1);return r}
  alternatives(a,b,moment,allowedModes=null){let cache=this.timetable(moment.base),prepared=this.prepareEndpoints(a,b,cache),first=this.search(a,b,moment,new Set,prepared,allowedModes);if(!first)return[];let out=[first],lines=[...new Set(first.steps.filter(x=>x.kind==='ride').map(x=>x.line))];for(const line of lines.slice(0,4)){let r=this.search(a,b,moment,new Set([line]),prepared,allowedModes);if(r&&r.arrival<=first.arrival+50&&!out.some(x=>x.signature===r.signature))out.push(r);if(out.length>=3)break}return out.sort((x,y)=>x.arrival-y.arrival||x.transfers-y.transfers).slice(0,3)}
  arriveBy(a,b,target,allowedModes=null){const targetDate=atMinute(target.base,target.minutes),targetMs=targetDate.getTime(),feasible=d=>{const m=serviceMoment(d),r=this.search(a,b,m,new Set,null,allowedModes);if(!r)return null;const arrivalDate=atMinute(r.base,r.arrival);if(arrivalDate.getTime()>targetMs+15000)return null;r.requestedArrivalDate=targetDate;r.arrivalDate=arrivalDate;return r};let upperMin=Math.floor(targetMs/60000),lowerMin=upperMin,best=null;for(let span=15;span<=1440;span+=span<120?15:30){lowerMin=Math.floor((targetMs-span*60000)/60000);best=feasible(new Date(lowerMin*60000));if(best)break}if(!best)return[];let lo=lowerMin,hi=upperMin;while(lo<hi){const mid=Math.ceil((lo+hi)/2),r=feasible(new Date(mid*60000));if(r){lo=mid;best=r}else hi=mid-1}best=feasible(new Date(lo*60000))||best;const out=[],seen=new Set,add=r=>{if(!r||seen.has(r.signature))return;const ad=atMinute(r.base,r.arrival);if(ad.getTime()>targetMs+15000)return;r.requestedArrivalDate=targetDate;r.arrivalDate=ad;seen.add(r.signature);out.push(r)};for(const delta of [0,-4,-8,-15,-25]){const d=new Date((lo+delta)*60000),m=serviceMoment(d);for(const r of this.alternatives(a,b,m,allowedModes))add(r)}add(best);return out.sort((x,y)=>y.departure-x.departure||x.arrival-y.arrival||x.transfers-y.transfers).slice(0,3)}
}
const router=new ExactRouter;window.LRExactRouter=router;if(typeof document==='undefined'||!document.getElementById('routeDate'))return;
let timeChoice='now',routeRestore=null,currentAlternatives=[],selectedAlternative=0;
function setDefaultDate(){let d=new Date;$('routeDate').value=localISO(d);$('routeTime').value=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function chosenDate(){if(timeChoice==='now')return new Date;let [y,m,d]=($('routeDate').value||localISO(new Date)).split('-').map(Number),[h,mi]=($('routeTime').value||'12:00').split(':').map(Number);return new Date(y,m-1,d,h,mi||0)}
function updateTimeButton(){let d=chosenDate(),now=timeChoice==='now',arrival=timeChoice==='arrival';$('routeTimeButton').querySelector('strong').textContent=now?'Partir maintenant':arrival?'Arriver à':'Départ à';$('routeTimeSummary').textContent=now?'Selon l’heure actuelle':`${d.toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})} à ${d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`}
function allowedTransitModes(){return new Set([...document.querySelectorAll('[data-route-mode]:checked')].map(x=>x.dataset.routeMode))}
function updateModeButton(){const allowed=allowedTransitModes(),all=allowed.size===4,labels={train:'train',metro:'métro',tram:'tram',bus:'bus'};$('routeSettingsBtn').textContent=all?'Modes':allowed.size?`${allowed.size} mode${allowed.size>1?'s':''}`:'Aucun mode';$('routeSettingsBtn').classList.toggle('filtered',!all);$('routeSettingsBtn').title=all?'Tous les modes sont autorisés':'Modes autorisés : '+[...allowed].map(x=>labels[x]).join(', ')}
setDefaultDate();updateTimeButton();updateModeButton();
$('routeTimeButton').addEventListener('click',e=>{e.stopPropagation();$('routeModesPopover').classList.add('hidden');$('routeTimePopover').classList.toggle('hidden')});
document.querySelectorAll('[data-time-choice]').forEach(b=>b.addEventListener('click',()=>{timeChoice=b.dataset.timeChoice;document.querySelectorAll('[data-time-choice]').forEach(x=>x.classList.toggle('active',x===b));$('customTimeFields').classList.toggle('disabled',timeChoice==='now')}));
$('applyRouteTime').addEventListener('click',()=>{updateTimeButton();$('routeTimePopover').classList.add('hidden')});
$('routeSettingsBtn').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();$('routeTimePopover').classList.add('hidden');$('routeModesPopover').classList.toggle('hidden')},{capture:true});
$('applyRouteModes').addEventListener('click',()=>{updateModeButton();$('routeModesPopover').classList.add('hidden')});
$('allRouteModes').addEventListener('click',()=>{document.querySelectorAll('[data-route-mode]').forEach(x=>x.checked=true);updateModeButton()});
document.querySelectorAll('[data-route-mode]').forEach(x=>x.addEventListener('change',updateModeButton));
document.addEventListener('click',e=>{if(!e.target.closest('.routeWhenRow')){$('routeTimePopover').classList.add('hidden');$('routeModesPopover').classList.add('hidden')}});
function enterRouteFocus(){if(!state.routeFocus)routeRestore={style:state.style,layers:{...state.layers},selectedLine:state.selectedLine,selectedKey:state.selectedKey,selectedGroup:state.selectedGroup};state.routeFocus=true;state.style='standard';state.layers.train=state.layers.metro=state.layers.tram=state.layers.bus=false;state.layers.poi=false;state.selectedLine=state.selectedKey=state.selectedGroup=null;$('lineInspector').classList.add('hidden');$('detailCard').classList.add('hidden')}
function closeRoute(){state.route=[];state.routeStops=[];state.routeFocus=false;if(routeRestore){state.style=routeRestore.style;Object.assign(state.layers,routeRestore.layers);state.selectedLine=routeRestore.selectedLine;state.selectedKey=routeRestore.selectedKey;state.selectedGroup=routeRestore.selectedGroup;routeRestore=null}$('routePanel').classList.add('hidden');currentAlternatives=[];syncModeUI();APP.lineList($('lineSearch').value);APP.redraw()}
$('closeRoute').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();closeRoute()},{capture:true});
function resolvePoint(key,input){if(state[key])return state[key];let r=APP.search($(input).value,1)[0];if(r){state[key]=r;$(input).value=r[2]}return r}
function fitActive(){APP.fitRoute();APP.redraw()}
function routePoint(item){return{x:+item[4],z:+item[5],name:item[2]}}
function iconForMode(m){m=String(m).toLowerCase();return m.includes('bus')?'BUS':m.includes('tram')?'T':m.includes('métro')?'M':'R'}
function renderAlternativeCard(r,i){let lines=r.steps.filter(x=>x.kind==='ride'),chips=lines.map(x=>`<span class="routeChip" style="background:${x.color}">${esc(x.line)}</span>`).join('<span class="routeArrow">›</span>')||'<span class="walkOnly">À pied</span>';return `<button class="journeyChoice ${i===selectedAlternative?'active':''}" data-alt="${i}"><div><strong>${fmtDuration(r.minutes)}</strong><small>${fmtClock(r.base,r.departure)} → ${fmtClock(r.base,r.arrival)}</small></div><div class="journeyChips">${chips}</div><span class="journeyMeta">${r.transfers?`${r.transfers} correspondance${r.transfers>1?'s':''}`:'Direct'} · ${Math.round(r.walkMinutes)} min à pied</span></button>`}
function stepHTML(s){let range=`${fmtClock(currentAlternatives[selectedAlternative].base,s.fromTime)}–${fmtClock(currentAlternatives[selectedAlternative].base,s.toTime)}`;if(s.kind==='ride'){let traffic=s.trafficDelay>.35?`<div class="trafficInline ${s.trafficDelay>=4?'heavy':''}"><strong>${esc(s.trafficLabel||'Trafic estimé')}</strong><span>+${Math.round(s.trafficDelay)} min par rapport à la fiche horaire</span></div>`:'';return `<div class="timelineStep rideStep" style="--stepColor:${s.color}"><div class="timelineRail"><span class="timelineBadge" style="background:${s.color}">${esc(s.line)}</span></div><div class="timelineContent"><div class="stepTop"><strong>${esc(s.from)} → ${esc(s.to)}</strong><time>${range}</time></div><div class="rideDestination">${esc(s.mode)} ${esc(s.line)} · direction ${esc(s.destination)}</div><div class="stepDetails"><span>Départ exact ${fmtClock(currentAlternatives[selectedAlternative].base,s.fromTime)}</span><span>${s.stops} arrêt${s.stops>1?'s':''}</span><span>Mission ${esc(s.tripCode)}</span></div>${traffic}</div></div>`}if(s.kind==='wait')return `<div class="timelineStep waitStep"><div class="timelineRail"><span>···</span></div><div class="timelineContent"><div class="stepTop"><strong>${esc(s.title)}</strong><time>${fmtDuration(s.minutes)}</time></div><div class="stepDetails"><span>Départ prévu à ${fmtClock(currentAlternatives[selectedAlternative].base,s.toTime)}</span></div></div></div>`;let transfer=s.kind==='transfer';return `<div class="timelineStep walkStep"><div class="timelineRail"><span>${transfer?'↗':'●'}</span></div><div class="timelineContent"><div class="stepTop"><strong>${esc(s.title)}</strong><time>${range}</time></div><div class="stepDetails"><span>${transfer?'Changement de ligne':fmtDistance(s.distance||0)}</span><span>${fmtDuration(s.minutes)}</span></div></div></div>`}
function selectAlternative(i){selectedAlternative=i;let r=currentAlternatives[i],constraint=r.requestedArrivalDate?` · arrivée souhaitée avant ${r.requestedArrivalDate.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`:'';enterRouteFocus();state.route=r.overlay;state.routeStops=r.stops;$('routeResults').innerHTML=`<div class="journeyOverview"><div class="journeyHeadline"><div><strong>${fmtDuration(r.minutes)}</strong><span>Départ ${fmtClock(r.base,r.departure)} · arrivée ${fmtClock(r.base,r.arrival)}</span></div><div class="exactPill">Horaires exacts</div></div><div class="journeyDate">${fmtDateTime(r.base,r.departure)} → ${fmtDateTime(r.base,r.arrival)}${constraint}</div></div><div class="journeyChoices">${currentAlternatives.map(renderAlternativeCard).join('')}</div><div class="journeyTimeline"><div class="timelineEndpoints"><span>${esc(r.a.name)}</span><span>${esc(r.b.name)}</span></div>${r.steps.map(stepHTML).join('')}</div>`;$('routeResults').querySelectorAll('[data-alt]').forEach(b=>b.addEventListener('click',()=>selectAlternative(+b.dataset.alt)));fitActive()}
function renderRoadRoute(r,mode,a,b){let color=mode==='walk'?'#20a36a':mode==='bike'?'#34a853':'#0a84ff',dep=r.departureDate||chosenDate(),arr=r.arrivalDate||new Date(dep.getTime()+r.minutes*60000);enterRouteFocus();state.route=[{coords:r.coords,color,width:7}];state.routeStops=[{x:a.x,z:a.z,color:'#0a84ff',label:a.name,major:true},{x:b.x,z:b.z,color:'#30b34a',label:b.name,major:true}];let steps=r.groups.map((g,i)=>`<div class="roadInstruction"><span>${i?i+1:'●'}</span><div><strong>${i?'Continuer sur':'Emprunter'} ${esc(g.name)}</strong><small>${fmtDistance(g.distance)}</small></div></div>`).join('');let traffic=mode==='drive'&&r.traffic?`<div class="trafficBanner ${r.delayMinutes>=6?'heavy':r.delayMinutes>=2?'dense':'fluid'}"><div><strong>${esc(r.traffic.label)}</strong><span>Trafic estimé pour l’heure de départ</span></div><b>${r.delayMinutes>=.6?'+'+Math.round(r.delayMinutes)+' min':'Peu de ralentissements'}</b></div><div class="trafficStats"><span>Vitesse moyenne estimée <strong>${Math.round(r.averageSpeed||0)} km/h</strong></span><span>Sans trafic <strong>${fmtDuration(r.baseMinutes||r.minutes)}</strong></span></div>`:'';$('routeResults').innerHTML=`<div class="journeyOverview"><div class="journeyHeadline"><div><strong>${fmtDuration(r.minutes)}</strong><span>${fmtDistance(r.distance)}</span></div><div class="exactPill estimate">${mode==='drive'?'Trafic estimé':'Estimation'}</div></div><div class="journeyDate">${esc(dep.toLocaleString('fr-FR',{weekday:'short',day:'numeric',month:'short'}))} · départ ${dep.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · arrivée ${arr.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}<br>${esc(a.name)} → ${esc(b.name)}</div></div>${traffic}<div class="roadInstructions">${steps}</div>`;fitActive()}
function roadArriveBy(a,b,mode,target){let dep=new Date(target),r=null;for(let i=0;i<5;i++){r=APP.roadRoute(a,b,mode,{date:dep});if(!r)return null;dep=new Date(target.getTime()-r.minutes*60000)}r=APP.roadRoute(a,b,mode,{date:dep});if(!r)return null;r.departureDate=dep;r.arrivalDate=new Date(dep.getTime()+r.minutes*60000);r.requestedArrivalDate=target;return r}
function calculateExact(){let ai=resolvePoint('routeFrom','fromInput'),bi=resolvePoint('routeTo','toInput');if(!ai||!bi){$('routeResults').innerHTML='<div class="routeError">Renseigne un départ et une arrivée.</div>';return}if(ai[0]===bi[0]&&ai[1]===bi[1]){$('routeResults').innerHTML='<div class="routeError">Le départ et l’arrivée sont identiques.</div>';return}let a=routePoint(ai),b=routePoint(bi),mode=state.routeMode,date=chosenDate();$('routeStatus').innerHTML=mode==='transit'?'<span class="routeSpinner"></span> Lecture des fiches horaires exactes et calcul des correspondances…':mode==='drive'?'<span class="routeSpinner"></span> Calcul de la voirie et du trafic à l’heure choisie…':'<span class="routeSpinner"></span> Calcul du chemin sur la voirie…';$('routeResults').innerHTML='';setTimeout(()=>{try{if(mode==='transit'){let allowed=allowedTransitModes();if(!allowed.size){$('routeResults').innerHTML='<div class="routeError">Sélectionne au moins un mode de transport dans « Modes ».</div>';return}let moment=serviceMoment(date),alts=timeChoice==='arrival'?router.arriveBy(a,b,moment,allowed):router.alternatives(a,b,moment,allowed);if(!alts.length){$('routeResults').innerHTML=`<div class="routeError">Aucun itinéraire compatible avec ${timeChoice==='arrival'?'l’heure d’arrivée':'l’heure de départ'} et les modes sélectionnés.</div>`;return}currentAlternatives=alts;selectedAlternative=0;selectAlternative(0)}else{let r=timeChoice==='arrival'?roadArriveBy(a,b,mode,date):APP.roadRoute(a,b,mode,{date});if(!r){$('routeResults').innerHTML='<div class="routeError">Aucun chemin n’a été trouvé sur la voirie.</div>';return}if(timeChoice!=='arrival'){r.departureDate=date;r.arrivalDate=new Date(date.getTime()+r.minutes*60000)}renderRoadRoute(r,mode,a,b)}}catch(err){console.error(err);$('routeResults').innerHTML=`<div class="routeError">Le calcul horaire a rencontré une erreur : ${esc(err.message||err)}</div>`}finally{$('routeStatus').textContent=''}},30)}
$('calculateRoute').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();calculateExact()},{capture:true});
// Map modes and line filters
function syncModeUI(){document.querySelectorAll('[data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===state.style));document.querySelectorAll('[data-layer]').forEach(x=>{if(x.dataset.layer in state.layers)x.checked=!!state.layers[x.dataset.layer]})}
$('showAllLines').addEventListener('click',()=>{state.visibleLineKeys=new Set(Object.keys(T.lineInfo));state.style='transport';state.layers.train=state.layers.metro=state.layers.tram=state.layers.bus=true;APP.lineList($('lineSearch').value);syncModeUI();APP.redraw()});
$('hideAllLines').addEventListener('click',()=>{state.visibleLineKeys.clear();state.selectedLine=state.selectedKey=state.selectedGroup=null;APP.lineList($('lineSearch').value);APP.redraw()});
document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{if(b.dataset.style==='standard'){state.style='standard';state.layers.train=state.layers.metro=state.layers.tram=state.layers.bus=false}else{state.style='transport';state.layers.train=state.layers.metro=state.layers.tram=true}syncModeUI();APP.redraw()},0)));
$('transportBtn').addEventListener('click',()=>setTimeout(syncModeUI,0));
document.querySelectorAll('[data-layer]').forEach(x=>x.addEventListener('change',()=>setTimeout(syncModeUI,0)));
// Close route with Escape while preserving the usual popover behavior.
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('routePanel').classList.contains('hidden')&&state.routeFocus)closeRoute()});
// Expose test hooks.
window.__LR_V5_TEST__={router,serviceMoment,calculateExact,selectAlternative,closeRoute,allowedTransitModes,chosenDate,get timeChoice(){return timeChoice}};
setTimeout(()=>{let t=$('toast');t.textContent='Plans Voyageur 8 · arrivée/départ, filtres de modes et tracés continus';t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2300)},1100);
})();
